import { FileNode } from '@/types/FileNode';

const GUEST_ID = '00000000-0000-0000-0000-000000000000';

export const mockFileTree: FileNode[] = [
  {
    id: 1,
    name: 'Documents',
    folder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 4096,
    mime: 'directory',
    storageKey: 'documents/',
  },
  {
    id: 2,
    name: 'Pictures',
    folder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 4096,
    mime: 'directory',
    storageKey: 'pictures/',
  },
  {
    id: 3,
    name: 'Music',
    folder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 4096,
    mime: 'directory',
    storageKey: 'music/',
  },
  {
    id: 4,
    name: 'report.docx',
    folder: false,
    parentId: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 12345,
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    storageKey: 'documents/report.docx',
  },
  {
    id: 5,
    name: 'presentation.pptx',
    folder: false,
    parentId: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 54321,
    mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    storageKey: 'documents/presentation.pptx',
  },
  {
    id: 6,
    name: 'vacation.jpg',
    folder: false,
    parentId: 2,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 123456,
    mime: 'image/jpeg',
    storageKey: 'pictures/vacation.jpg',
  },
  {
    id: 7,
    name: 'song.mp3',
    folder: false,
    parentId: 3,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 345678,
    mime: 'audio/mpeg',
    storageKey: 'music/song.mp3',
  },
  {
    id: 8,
    name: 'Subfolder',
    folder: true,
    parentId: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 4096,
    mime: 'directory',
    storageKey: 'documents/Subfolder/',
  },
  {
    id: 9,
    name: 'nested-report.docx',
    folder: false,
    parentId: 8,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isDeleted: false,
    deletedAt: null,
    ownerId: GUEST_ID,
    size: 12345,
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    storageKey: 'documents/Subfolder/nested-report.docx',
  },
];
