import { FileNode } from '@/types/FileNode';

export const mockFileTree: FileNode[] = [
  {
    id: '1',
    name: 'Documents',
    isFolder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 4096,
  },
  {
    id: '2',
    name: 'Pictures',
    isFolder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 4096,
  },
  {
    id: '3',
    name: 'Music',
    isFolder: true,
    parentId: null,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 4096,
  },
  {
    id: '4',
    name: 'report.docx',
    isFolder: false,
    parentId: '1',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 12345,
  },
  {
    id: '5',
    name: 'presentation.pptx',
    isFolder: false,
    parentId: '1',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 54321,
  },
  {
    id: '6',
    name: 'vacation.jpg',
    isFolder: false,
    parentId: '2',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 123456,
  },
  {
    id: '7',
    name: 'song.mp3',
    isFolder: false,
    parentId: '3',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 345678,
  },
    {
    id: '8',
    name: 'Subfolder',
    isFolder: true,
    parentId: '1',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 4096,
  },
    {
    id: '9',
    name: 'nested-report.docx',
    isFolder: false,
    parentId: '8',
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    ownerId: 'user-1',
    size: 12345,
  },
];
